SNPs: /dcl01/hansen/data/arazi/gtex_count/genotype/biallelic_SNP_gr.rda
coverageCutoff: 4
studyMetadata: /dcs04/hansen/data/recount_genotype/pipeline/metadata/all_SRA.csv
outputMetadata: /dcs04/hansen/data/recount_genotype/pipeline/AggregateFiles/all_SRA.csv
outputFolder: /dcs04/hansen/data/recount_genotype/pipeline
tempFolder: /dcs04/hansen/data/recount_genotype/pipeline/tmp
model: /dcs04/hansen/data/recount_genotype/training/GTEx_Blended_Tissue_Training/model_MS_GTEx_Blended_Tissue_Training.rds
modelLattice: /dcs04/hansen/data/recount_genotype/training/GTEx_Blended_Tissue_Training/model_MS_GTEx_Blended_Tissue_Training_lattice.rds
modelPrior: /dcs04/hansen/data/recount_genotype/training/GTEx_Blended_Tissue_Training/p_Zg_GTEx_Blended_Tissue_Training.rds
accuracyModel: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_accuracy_model/GTEx_Blended_Tissue_Training_accuracy_model.rds
accuracyModelLattice: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_accuracy_model/GTEx_Blended_Tissue_Training_accuracy_model_lattice.rds
