SNPs: /dcs04/hansen/data/recount_genotype/biallelic_snps/biallelic_SNP_gr.rds
coverageCutoff: 4
studyMetadata: /dcs04/hansen/data/recount_genotype/pipeline/metadata/all_SRA.csv
outputMetadata: /dcs04/hansen/data/recount_genotype/pipeline/AggregateFiles/all_SRA.csv
outputFolder: /dcs04/hansen/data/recount_genotype/pipeline
tempFolder: /dcs04/hansen/data/recount_genotype/pipeline/tmp
model: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_genotyping_model/GTEx_Blended_Tissue_Training_genotyping_model.rds
modelLattice: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_genotyping_model/GTEx_Blended_Tissue_Training_genotyping_lattice.rds
modelPrior: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_genotyping_model/GTEx_Blended_Tissue_Training_genotyping_prior.rds
accuracyModel: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_accuracy_model/GTEx_Blended_Tissue_Training_accuracy_model.rds
accuracyModelLattice: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_accuracy_model/GTEx_Blended_Tissue_Training_accuracy_model_lattice.rds
