SNPs: /dcl01/hansen/data/arazi/gtex_count/genotype/biallelic_SNP_gr.rda
genotypedVCF: /dcl01/hansen/data/gtex_private/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
studyMetadata: GTEx_Blended_Tissue_Training_metadata.csv
outputFolder: /dcs04/hansen/data/recount_genotype/pipeline
tempFolder: /dcs04/hansen/data/recount_genotype/pipeline/tmp
modelMetadata: model_metadata.csv