SNPs: /dcl01/hansen/data/arazi/gtex_count/genotype/biallelic_SNP_gr.rda
genotypedVCF: /dcl01/hansen/data/gtex_private/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
coverageCutoff: 4
studyMetadata: tcga.normal.metadata.csv
outputMetadata: /dcs04/hansen/data/recount_genotype/pipeline/AggregateFiles/tcga.normal.metadata.csv
outputFolder: /dcs04/hansen/data/recount_genotype/pipeline
tempFolder: /dcs04/hansen/data/recount_genotype/pipeline/tmp
model: /dcs04/hansen/data/recount_genotype/training/GTEx_Blended_Tissue_Training/model_MS_GTEx_Blended_Tissue_Training.rds
modelLattice: /dcs04/hansen/data/recount_genotype/training/GTEx_Blended_Tissue_Training/model_MS_GTEx_Blended_Tissue_Training_lattice.rds
modelPrior: /dcs04/hansen/data/recount_genotype/training/GTEx_Blended_Tissue_Training/p_Zg_GTEx_Blended_Tissue_Training.rds
accuracyModel: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_accuracy_model/GTEx_Blended_Tissue_Training_accuracy_model.rds
accuracyModelLattice: /dcs04/hansen/data/recount_genotype/pipeline/GTEx_Blended_Tissue_Training/train_accuracy_model/GTEx_Blended_Tissue_Training_accuracy_model_lattice.rds
